services:
  - type: web
    name: medcontrol
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn medcontrol_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: medcontrol_project.settings
      - key: PYTHON_VERSION
        value: 3.12.0
